#!/bin/bash
#
# Blackbox5 Hook: Create Session Record
# Event: SessionEnd
# Purpose: Create structured session folder for scalability
#

set -euo pipefail

INPUT=$(cat)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // "unknown"')
TRANSCRIPT_PATH=$(echo "$INPUT" | jq -r '.transcript_path // empty')
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
TIMESTAMP_UNIX=$(date +%s)

MEMORY_BASE="${BLACKBOX5_MEMORY_PATH:-./blackbox5/5-project-memory/lumelle}"
SESSIONS_DIR="$MEMORY_BASE/operations/sessions"

mkdir -p "$SESSIONS_DIR"
SESSION_DIR="$SESSIONS_DIR/session-${TIMESTAMP_UNIX}"
mkdir -p "$SESSION_DIR"

SESSION_START_FILE="$MEMORY_BASE/.session_start"
if [[ -f "$SESSION_START_FILE" ]]; then
    START_TIME=$(cat "$SESSION_START_FILE")
    END_TIME=$(date +%s)
    DURATION=$((END_TIME - START_TIME))
    DURATION_MINUTES=$((DURATION / 60))
else
    DURATION_MINUTES=0
fi

WORKING_DIR=$(pwd)
GIT_BRANCH=$(git branch --show-current 2>/dev/null || echo "N/A")
GIT_STATUS=$(git status --short 2>/dev/null | wc -l | tr -d ' ')

cat > "$SESSION_DIR/context.json" << EOF
{
  "session_id": "$SESSION_ID",
  "timestamp": "$TIMESTAMP",
  "timestamp_unix": $TIMESTAMP_UNIX,
  "working_directory": "$WORKING_DIR",
  "git_branch": "$GIT_BRANCH",
  "git_changes_count": $GIT_STATUS,
  "duration_minutes": $DURATION_MINUTES,
  "project_memory_path": "$MEMORY_BASE"
}
EOF

cat > "$SESSION_DIR/metrics.json" << EOF
{
  "session_id": "$SESSION_ID",
  "duration_minutes": $DURATION_MINUTES,
  "git_changes": $GIT_STATUS,
  "timestamp": "$TIMESTAMP",
  "status": "completed",
  "reflection_pending": true
}
EOF

if [[ -n "$TRANSCRIPT_PATH" && -f "$TRANSCRIPT_PATH" ]]; then
    cp "$TRANSCRIPT_PATH" "$SESSION_DIR/transcript.jsonl"
else
    echo "[]" > "$SESSION_DIR/transcript.jsonl"
fi

cat > "$SESSION_DIR/README.md" << EOF
# Session: $SESSION_ID

**Timestamp**: $TIMESTAMP
**Duration**: $DURATION_MINUTES minutes
**Location**: $WORKING_DIR
**Git Branch**: $GIT_BRANCH

## Files

- **transcript.jsonl** - Full conversation transcript
- **context.json** - Session context and metadata
- **metrics.json** - Session metrics and stats

## Reflection

Reflection will be generated asynchronously by the Stop hook using Haiku model.

---
*Auto-generated by Blackbox5 SessionEnd hook*
EOF

echo "[$TIMESTAMP] Session created: $SESSION_DIR (duration: ${DURATION_MINUTES}m)" >> "$MEMORY_BASE/operations/session-log.txt"

if [[ -f "$SESSION_START_FILE" ]]; then
    rm -f "$SESSION_START_FILE"
fi

exit 0
