#!/bin/bash
#
# Blackbox5 Hook: Extract & Persist Memories
# Event: SessionEnd
# Purpose: Organizational learning from every session
#

set -euo pipefail

# Read input from Claude Code
data=$(cat)
session_id=$(echo "$data" | jq -r '.session_id // "unknown"')
timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Memory paths
MEMORY_BASE="${BLACKBOX5_MEMORY_PATH:-./5-project-memory/siso-internal}"
DECISIONS_DIR="$MEMORY_BASE/decisions"
KNOWLEDGE_DIR="$MEMORY_BASE_DIR/knowledge"

# Ensure directories exist
mkdir -p "$DECISIONS_DIR" "$KNOWLEDGE_DIR"

# Session memory file
SESSION_FILE="$MEMORY_BASE/sessions/session_${session_id}_$(date +%s).md"

# Extract session summary (if available)
summary=$(echo "$data" | jq -r '.summary // "No summary provided"')

# Create session record
cat > "$SESSION_FILE" << EOF
# Session: $session_id

**Date**: $timestamp
**Type**: Claude Code Session

## Summary
$summary

## Artifacts
$(echo "$data" | jq -r '.artifacts // []' | jq -r '.[] | "- \(.)"')

## Files Modified
$(echo "$data" | jq -r '.files_modified // []' | jq -r '.[] | "- \(.)"')

---

*Auto-generated by Blackbox5 hooks at $timestamp*
EOF

# Analyze for potential decisions
# Look for decision-like patterns in recent work
if ls "$MEMORY_BASE/tasks/active/"*.md 2>/dev/null | head -1 | grep -q .; then
  # Tasks were completed - may have produced decisions
  echo "[$timestamp] Session completed with active tasks" >> "$MEMORY_BASE/session-timeline.txt"
fi

# Check for new patterns (frequently edited files)
if [[ -f "$MEMORY_BASE/WORK-LOG.md" ]]; then
  # Find files edited >3 times in this session
  frequently_edited=$(grep "session: $session_id" "$MEMORY_BASE/WORK-LOG.md" 2>/dev/null | \
    grep -o 'file: "[^"]*"' | cut -d'"' -f2 | sort | uniq -c | sort -rn | \
    awk '$1 > 3 {print $2}')

  if [[ -n "$frequently_edited" ]]; then
    echo "[$timestamp] Frequently edited files this session:" >> "$MEMORY_BASE/pattern-detection.txt"
    echo "$frequently_edited" >> "$MEMORY_BASE/pattern-detection.txt"
  fi
fi

exit 0
