#!/bin/bash
# subagent-tracking.sh - Smart subagent start/stop tracking for BB5
# Purpose: Track agent lifecycle without environment variables
# Usage: Called with "start" or "stop" argument

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BB5_DIR="$PROJECT_ROOT/5-project-memory/blackbox5"
COMM_DIR="$BB5_DIR/.autonomous/agents/communications"

EVENT_TYPE="${1:-start}"  # "start" or "stop"

# =============================================================================
# SELF-DISCOVERY: Detect agent from context
# =============================================================================

detect_agent_info() {
    local cwd="$(pwd)"
    local agent_type="unknown"
    local agent_id="unknown"
    local parent_task=""

    # Method 1: Run directory path
    if [[ "$cwd" == *"/planner/"* ]] || [[ "${RALF_RUN_DIR:-}" == *"/planner/"* ]]; then
        agent_type="planner"
        agent_id="planner-$(date +%s)"
    elif [[ "$cwd" == *"/executor/"* ]] || [[ "${RALF_RUN_DIR:-}" == *"/executor/"* ]]; then
        agent_type="executor"
        agent_id="executor-$(date +%s)"
        # Try to find claimed task
        if [ -f "$COMM_DIR/queue.yaml" ]; then
            parent_task=$(grep -B5 "claimed_by" "$COMM_DIR/queue.yaml" | grep "task_id:" | tail -1 | cut -d':' -f2 | tr -d ' ' || echo "")
        fi
    elif [[ "$cwd" == *"/architect/"* ]] || [[ "${RALF_RUN_DIR:-}" == *"/architect/"* ]]; then
        agent_type="architect"
        agent_id="architect-$(date +%s)"
    fi

    # Method 2: Check run folder name
    if [ -n "${RALF_RUN_ID:-}" ]; then
        agent_id="${agent_type}-${RALF_RUN_ID}"
    fi

    echo "$agent_type|$agent_id|$parent_task"
}

# =============================================================================
# LOG TO EVENTS.YAML
# =============================================================================

log_event() {
    local agent_type="$1"
    local agent_id="$2"
    local parent_task="$3"
    local event="$4"

    local events_file="$COMM_DIR/events.yaml"
    local timestamp=$(date -Iseconds)

    # Ensure directory exists
    mkdir -p "$COMM_DIR"

    # Create events.yaml if doesn't exist
    if [ ! -f "$events_file" ]; then
        echo "events:" > "$events_file"
    fi

    # Append event
    cat >> "$events_file" << EOF

- timestamp: "$timestamp"
  type: agent_$event
  agent_type: "$agent_type"
  agent_id: "$agent_id"
  parent_task: "$parent_task"
  source: "hook"
EOF

    echo "✓ Event logged: $event $agent_type"
}

# =============================================================================
# UPDATE AGENT STATE
# =============================================================================

update_agent_state() {
    local agent_type="$1"
    local event="$2"

    local state_file="$COMM_DIR/agent-state.yaml"
    local timestamp=$(date -Iseconds)

    mkdir -p "$COMM_DIR"

    # Read current state or create new
    if [ -f "$state_file" ]; then
        # Update existing state
        if [ "$event" = "start" ]; then
            sed -i.bak "s/${agent_type}_status:.*/${agent_type}_status: active/" "$state_file" 2>/dev/null || true
            sed -i.bak "s/${agent_type}_last_start:.*/${agent_type}_last_start: $timestamp/" "$state_file" 2>/dev/null || true
            rm -f "$state_file.bak"
        else
            sed -i.bak "s/${agent_type}_status:.*/${agent_type}_status: idle/" "$state_file" 2>/dev/null || true
            sed -i.bak "s/${agent_type}_last_stop:.*/${agent_type}_last_stop: $timestamp/" "$state_file" 2>/dev/null || true
            rm -f "$state_file.bak"
        fi
    else
        # Create new state file
        cat > "$state_file" << EOF
# Agent State Tracking
# Auto-generated by subagent-tracking hook

planner_status: $([ "$agent_type" = "planner" ] && [ "$event" = "start" ] && echo "active" || echo "idle")
planner_last_start: $([ "$agent_type" = "planner" ] && [ "$event" = "start" ] && echo "$timestamp" || echo "null")
planner_last_stop: $([ "$agent_type" = "planner" ] && [ "$event" = "stop" ] && echo "$timestamp" || echo "null")

executor_status: $([ "$agent_type" = "executor" ] && [ "$event" = "start" ] && echo "active" || echo "idle")
executor_last_start: $([ "$agent_type" = "executor" ] && [ "$event" = "start" ] && echo "$timestamp" || echo "null")
executor_last_stop: $([ "$agent_type" = "executor" ] && [ "$event" = "stop" ] && echo "$timestamp" || echo "null")

architect_status: $([ "$agent_type" = "architect" ] && [ "$event" = "start" ] && echo "active" || echo "idle")
architect_last_start: $([ "$agent_type" = "architect" ] && [ "$event" = "start" ] && echo "$timestamp" || echo "null")
architect_last_stop: $([ "$agent_type" = "architect" ] && [ "$event" = "stop" ] && echo "$timestamp" || echo "null")
EOF
    fi
}

# =============================================================================
# MAIN
# =============================================================================

# Detect agent info
AGENT_INFO=$(detect_agent_info)
AGENT_TYPE=$(echo "$AGENT_INFO" | cut -d'|' -f1)
AGENT_ID=$(echo "$AGENT_INFO" | cut -d'|' -f2)
PARENT_TASK=$(echo "$AGENT_INFO" | cut -d'|' -f3)

# Log event
log_event "$AGENT_TYPE" "$AGENT_ID" "$PARENT_TASK" "$EVENT_TYPE"

# Update agent state
update_agent_state "$AGENT_TYPE" "$EVENT_TYPE"

# Output for Claude
OUTPUT=$(cat << EOF
{
  "hookSpecificOutput": {
    "hookEventName": "Subagent$(echo "$EVENT_TYPE" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')",
    "additionalContext": "Agent $AGENT_ID ($AGENT_TYPE) has $EVENT_TYPE. Check $COMM_DIR/agent-state.yaml for current system state.",
    "agentType": "$AGENT_TYPE",
    "agentId": "$AGENT_ID",
    "parentTask": "$PARENT_TASK"
  }
}
EOF
)

echo "$OUTPUT"
