#!/bin/bash
#
# Blackbox5 Hooks Status Check
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "Blackbox5 Hooks Status"
echo "===================="
echo ""

# Check if memory path exists
MEMORY_PATH="${BLACKBOX5_MEMORY_PATH:-./5-project-memory/siso-internal}"

if [[ -d "$MEMORY_PATH" ]]; then
  echo "✓ Memory path exists: $MEMORY_PATH"
else
  echo "✗ Memory path not found: $MEMORY_PATH"
  echo "  Creating..."
  mkdir -p "$MEMORY_PATH"/{decisions,knowledge,operations,sessions}
fi

# Check required directories
required_dirs=(
  "decisions"
  "knowledge"
  "operations"
  "sessions"
)

echo ""
echo "Checking memory structure..."
for dir in "${required_dirs[@]}"; do
  dir_path="$MEMORY_PATH/$dir"
  if [[ -d "$dir_path" ]]; then
    echo "  ✓ $dir/"
  else
    echo "  ✗ $dir/ (missing)"
    mkdir -p "$dir_path"
    echo "    Created: $dir_path"
  fi
done

# Check WORK-LOG.md
WORK_LOG="$MEMORY_PATH/WORK-LOG.md"
if [[ ! -f "$WORK_LOG" ]]; then
  echo ""
  echo "Creating WORK-LOG.md..."
  cat > "$WORK_LOG" << 'EOF'
# Work Log

This file tracks all activity automatically via Blackbox5 hooks.

## Recent Activity

<!--
  Auto-generated by .claude/hooks/auto-log-activity.sh
  Do not edit manually
-->

EOF
  echo "  ✓ Created: $WORK_LOG"
fi

echo ""
echo "Status check complete!"
echo ""
echo "Environment variables:"
echo "  BLACKBOX5_ENGINE_PATH=${BLACKBOX5_ENGINE_PATH:-./2-engine}"
echo "  BLACKBOX5_MEMORY_PATH=${BLACKBOX5_MEMORY_PATH:-./5-project-memory/siso-internal}"
echo "  BLACKBOX5_CONTEXT_THRESHOLD=${BLACKBOX5_CONTEXT_THRESHOLD:-80}"
echo "  BLACKBOX5_SESSION_TIMEOUT=${BLACKBOX5_SESSION_TIMEOUT:-14400}"
