#!/bin/bash
# Setup environment variables for BlackBox5 APIs
# This script helps configure all required API keys

set -e

echo "========================================"
echo "BlackBox5 Environment Setup"
echo "========================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

ENV_FILE="/opt/blackbox5/config/.env"
ENV_EXAMPLE="/opt/blackbox5/config/.env.example"

echo "This script will set up environment variables for BlackBox5 APIs."
echo ""

# Check if .env file exists
if [ -f "$ENV_FILE" ]; then
    echo "Found existing .env file at $ENV_FILE"
    read -p "Do you want to backup it? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        cp "$ENV_FILE" "$ENV_FILE.backup.$(date +%Y%m%d_%H%M%S)"
        echo "Backup created: $ENV_FILE.backup.$(date +%Y%m%d_%H%M%S)"
    fi
fi

echo ""
echo "========================================"
echo "Configuring API Keys"
echo "========================================"
echo ""

# Create/clear .env file
cat > "$ENV_FILE" << 'EOF'
# BlackBox5 API Keys Configuration
# Generated by setup-env.sh on $(date)
EOF

# Kimi CISO Key
echo "1. Kimi CISO Key (Primary)"
echo "   This is the most reliable Kimi key (30 pound plan)"
read -p "   Press Enter to use default or enter custom key: " KIMI_CISO_KEY
if [ -z "$KIMI_CISO_KEY" ]; then
    KIMI_CISO_KEY="sk-kimi-YC3tlmLzogkd2ZMHdPwMMth3hV9r72aC5lk3kQTYI014GFjBN0VPcKfe6wczYlGr"
    echo "   Using default CISO key"
fi
echo "export KIMI_CISO_KEY='$KIMI_CISO_KEY'" >> "$ENV_FILE"
echo -e "${GREEN}✓ Kimi CISO key configured${NC}"
echo ""

# Kimi Trial Keys
echo "2. Kimi Trial Keys (8 keys)"
echo "   These are backup keys for load balancing"
for i in {02..08}; do
    VAR_NAME="KIMI_TRIAL_KEY_$(printf '%02d' $i)"
    read -p "   $VAR_NAME (press Enter to skip): " KEY_VALUE
    if [ -n "$KEY_VALUE" ]; then
        echo "export $VAR_NAME='$KEY_VALUE'" >> "$ENV_FILE"
        echo -e "${GREEN}✓ $VAR_NAME configured${NC}"
    else
        echo "export $VAR_NAME=''" >> "$ENV_FILE"
        echo -e "${YELLOW}⚠ $VAR_NAME skipped${NC}"
    fi
done
echo ""

# Anthropic API Key
echo "3. Anthropic API Key (Claude Code CLI)"
echo "   Required for complex reasoning tasks"
read -p "   Enter ANTHROPIC_API_KEY (or press Enter to skip): " ANTHROPIC_KEY
if [ -n "$ANTHROPIC_KEY" ]; then
    echo "export ANTHROPIC_API_KEY='$ANTHROPIC_KEY'" >> "$ENV_FILE"
    echo -e "${GREEN}✓ ANTHROPIC_API_KEY configured${NC}"
else
    echo "export ANTHROPIC_API_KEY=''" >> "$ENV_FILE"
    echo -e "${YELLOW}⚠ ANTHROPIC_API_KEY skipped${NC}"
fi
echo ""

# Nvidia Kimi Key
echo "4. Nvidia Kimi API Key"
echo "   Required for video/vision tasks"
read -p "   Enter NVIDIA_KIMI_KEY (or press Enter to skip): " NVIDIA_KEY
if [ -n "$NVIDIA_KEY" ]; then
    echo "export NVIDIA_KIMI_KEY='$NVIDIA_KEY'" >> "$ENV_FILE"
    echo -e "${GREEN}✓ NVIDIA_KIMI_KEY configured${NC}"
else
    echo "export NVIDIA_KIMI_KEY=''" >> "$ENV_FILE"
    echo -e "${YELLOW}⚠ NVIDIA_KIMI_KEY skipped${NC}"
fi
echo ""

# LiteLLM Master Key
echo "5. LiteLLM Master Key"
echo "   Required for litellm proxy admin access"
read -p "   Enter LITELLM_MASTER_KEY (or press Enter to skip): " LITELLM_KEY
if [ -n "$LITELLM_KEY" ]; then
    echo "export LITELLM_MASTER_KEY='$LITELLM_KEY'" >> "$ENV_FILE"
    echo -e "${GREEN}✓ LITELLM_MASTER_KEY configured${NC}"
else
    echo "export LITELLM_MASTER_KEY=''" >> "$ENV_FILE"
    echo -e "${YELLOW}⚠ LITELLM_MASTER_KEY skipped${NC}"
fi
echo ""

# Alert Webhook URL (optional)
echo "6. Alert Webhook URL (Optional)"
echo "   Used for sending alerts about API issues"
read -p "   Enter ALERT_WEBHOOK_URL (or press Enter to skip): " WEBHOOK_URL
if [ -n "$WEBHOOK_URL" ]; then
    echo "export ALERT_WEBHOOK_URL='$WEBHOOK_URL'" >> "$ENV_FILE"
    echo -e "${GREEN}✓ ALERT_WEBHOOK_URL configured${NC}"
else
    echo "export ALERT_WEBHOOK_URL=''" >> "$ENV_FILE"
    echo -e "${YELLOW}⚠ ALERT_WEBHOOK_URL skipped${NC}"
fi
echo ""

# Copy existing values from task-agent-env.txt
echo "7. Copying existing configuration..."
if [ -f "/opt/blackbox5/task-agent-env.txt" ]; then
    echo "" >> "$ENV_FILE"
    echo "# ========================================" >> "$ENV_FILE"
    echo "# Existing Configuration" >> "$ENV_FILE"
    echo "# ========================================" >> "$ENV_FILE"
    cat "/opt/blackbox5/task-agent-env.txt" >> "$ENV_FILE"
    echo -e "${GREEN}✓ Existing configuration copied${NC}"
fi

echo ""
echo "========================================"
echo "Setup Complete!"
echo "========================================"
echo ""
echo "Environment file created: $ENV_FILE"
echo ""
echo "To activate the environment variables, run:"
echo ""
echo "  source $ENV_FILE"
echo ""
echo "Or add to your ~/.bashrc or ~/.zshrc:"
echo ""
echo "  echo 'source $ENV_FILE' >> ~/.bashrc"
echo "  source ~/.bashrc"
echo ""
echo "========================================"
echo "Next Steps"
echo "========================================"
echo ""
echo "1. Activate environment:"
echo "   source $ENV_FILE"
echo ""
echo "2. Test all APIs:"
echo "   bash /opt/blackbox5/scripts/test-all-apis.sh"
echo ""
echo "3. Update OpenClaw configuration:"
echo "   Review ~/.openclaw/openclaw-api-config.json"
echo ""
echo "4. Read documentation:"
echo "   cat /opt/blackbox5/config/api-setup-complete.md"
echo ""
